### ISSUE TITLE
[GALTLC] Teleconference - Module crashes on initialization

### ISSUE THREAD

**Issue by tuday2** [mbbsemu/MBBSEmu#105]
**Module Information**
* Identifier: GALTLC
* Module Name: Teleconference
* Version: 6.25?

**Describe the bug**
Module crashes on initialization

**To Reproduce**
1. Add module
2. Run MBBSEmu

**Expected behavior**
Enter teleconference

**Screenshots**
```
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:0258')
   at MBBSEmu.Memory.MemoryCore.GetWord(UInt16 segment, UInt16 offset)
   at MBBSEmu.CPU.CpuCore.GetOperandValueUInt16(OpKind opKind, EnumOperandType operandType)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**API Report**
{"UniqueIdentifier":"GALTLC","File":"GALTLC.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[403,401,629,476,786,624,628,543,330,516,600,578,381,487,650,566,441,389,68,437,456,492,589,331,520,459,474,625,713,347,137,512,574,511,335,77,658,194,468,463,475,350,340,460,352,458,785,783,417,559,549,82,482,701,86,522,630,402,572,348,119,113,151,544,571,167],"GALMSG":[10,7],"GALGSBL":[60,30,62,63,64,21,4,6,7]}}

**Comment by enusbaum** [comment]
`MAJORBBS.600` is **TJOINROU**, `void (*tjoinrou)();`

This appears to be a function pointer that is set and executed when a given event occurs, most likely when you join the Tele-Conference. Similar to the routines that are registered during `register_module()`
