### ISSUE TITLE
[MUICHAOS] Swords of Chaos - Error during 1ST run of game (never sets up items)

### ISSUE THREAD

**Issue by tuday2** [mbbsemu/MBBSEmu#169]
**Module Information**
* Identifier: MUICHAOS
* Module Name: Swords of Chaos
* Version: 4.17

**Describe the bug**
Error during 1ST run of game (never sets up items), will initialize on second run but unable to move once entering realm, only exit is "out" and does not process command

**To Reproduce**
1. Enter module
2. Create character
3. "E"xplore the Realm
4. See error/behavior

**Expected behavior**
Able to move around realm

**Screenshots**
 ```
**===Error occurs on 1ST run only===**
AUDIT DETAIL: INSTALLING ITEMS
2020-10-06 05:51:48.1231 Warn MBBSEmu.HostProcess.ExportedModules.Majorbbs.f_read Attempting to read EOF file, returning null pointer
2020-10-06 05:51:48.1461 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 535:SETCNF
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 535:SETCNF')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```
Main Menu:
![Screenshot 2020-10-06 062215-555](https://user-images.githubusercontent.com/27604078/95195539-4e9aea00-079c-11eb-8406-6807a403fb4a.jpg)

"E"xplore Realm
![Screenshot 2020-10-06 062128-444](https://user-images.githubusercontent.com/27604078/95195485-375bfc80-079c-11eb-9259-e6854ed642d2.jpg)

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100220-5

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS:535` is `SETCNF` looks like it **SETS** a value in the currently open MSG file. 

![image](https://user-images.githubusercontent.com/1139047/95339769-6d73ac00-0882-11eb-92c6-5deb8cb76691.png)

It then calls `APPLYEM` (`MAJORBBS.73`) to save the new values to the MSG file.

**Comment by tuday2** [comment]
### MBBSEmu Build 100920-7 - Update -- No more error message on initialization, but cannot move out of starting room (issue in screenshot above)

```
2020-11-08 23:12:47.5292 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set soft-CR character 0A on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:47.7419 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set hard-CR character 0D on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:47.7469 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set soft-CR character 0A on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:48.0092 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set hard-CR character 0D on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:48.0126 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set soft-CR character 0A on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:48.3252 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set hard-CR character 0D on Channel 0 (Ignored -- only for ASCII mode)
2020-11-08 23:12:48.3252 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke Set soft-CR character 0A on Channel 0 (Ignored -- only for ASCII mode)
```

**Comment by tuday2** [comment]
![image](https://user-images.githubusercontent.com/27604078/102722207-30398a80-42c5-11eb-87da-dfbb825fbe82.png)
![image](https://user-images.githubusercontent.com/27604078/102722212-392a5c00-42c5-11eb-9cb1-7d7b9bee9c7e.png)
