### ISSUE TITLE
[BSSCRAK] CrAcKeD! - Unknown Exported Function Ordinal in MAJORBBS: 82:BAUDAT

### ISSUE THREAD

**Issue by ftoledo** [mbbsemu/MBBSEmu#509]
**Module Information**
* Identifier [BSSCRAK]
* Module Name [Cracked!]
* Version [1.0]

**Describe the bug**
Crash at start game

The game run for users with has MASTER KEY in demo mode

**To Reproduce**

add master key to user:
/sys addkey user master

start the game from menu

```
2021-10-31 02:13:57.8527 Debug MBBSEmu.HostProcess.ExportedModules.Majorbbs.setmbk (BSSCRAK) Enqueue Previous MCV File: BSSCRAK.MCV (Pointer: FFFF:0000)
2021-10-31 02:13:57.8527 Debug MBBSEmu.HostProcess.ExportedModules.Majorbbs.setmbk (BSSCRAK) Set Current MCV File: BSSCRAK.MCV (Pointer: FFFF:0000)
2021-10-31 02:13:57.8532 Debug MBBSEmu.HostProcess.ExportedModules.Majorbbs.setbtv (BSSCRAK) Setting current Btrieve file to BSSCRAK.DAT (1000:AC22)
2021-10-31 02:13:57.8532 Debug MBBSEmu.HostProcess.ExportedModules.Majorbbs.haskey (BSSCRAK) Returning 1 for Haskey(MASTER)
2021-10-31 02:13:57.8648 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 82:BAUDAT
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 82:BAUDAT')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.Run(String moduleName, FarPtr routine, UInt16 channelNumber, Boolean simulateCallFar, Queue`1 initialStackValues)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abortado

```

**Comment by ftoledo** [comment]
Original installer:

[bsscrak1.zip](https://github.com/mbbsemu/MBBSEmu/files/7448160/bsscrak1.zip)

**Comment by tuday2** [comment]
![image](https://user-images.githubusercontent.com/27604078/139571877-8b012279-6c52-40f8-8faf-84268e534e15.png)

**Comment by tuday2** [comment]
I stubbed out both of these and the game plays great (I don't think we need either of them).

**Comment by tuday2** [comment]
I did notice a bug when doing testing with multiple users playing. The game turns on the secure echo and basically keeps you in secure echo the entire time you are playing -- this seems to be bleeding over to other channels or at least sporadically showing up in other places (screenshot below showing a sign up while another user is playing the game)

![image](https://user-images.githubusercontent.com/27604078/139572212-2079b17e-f9f3-4c6d-a8e6-6955d1f1698e.png)

**Comment by tuday2** [comment]
Screenshot of gameplay:

![image](https://user-images.githubusercontent.com/27604078/139572251-64518008-e97b-4f8d-9f39-8737a06b4676.png)

![image](https://user-images.githubusercontent.com/27604078/139572240-2dda23f5-6535-49da-81ac-0b23dab70c46.png)
