### ISSUE TITLE
[WDGBSTAL] The Bathroom Stall - Unknown Exported Function Ordinal in MAJORBBS: 69:ALLDGS

### ISSUE THREAD

**Issue by ftoledo** [mbbsemu/MBBSEmu#511]
**Module Information**
* Identifier [WDGBSTAL]
* Module Name [The Bathroom Stall]
* Version [2.1i]

**Describe the bug**
Sorry i will mix two bugs here i think that these are related:

First, enter the "Male" or Female room, the module hang,
Maybe the module is not receiving the sex value of the user

```
2021-10-31 17:45:37.5067 Info MBBSEmu.HostProcess.MbbsHost.CallModuleRoutine Calling lonrou on module WDGBSTAL for channel 0
2021-10-31 17:45:37.5067 Warn MBBSEmu.HostProcess.ExportedModules.Majorbbs.strcpy Source (0004:020F) is NULL
```

**To Reproduce**
1. Enter the game
2. Hit 'M' or 'F'
3. The input hang

Then if you hit 'U' for Unisex room, the game continue: 

4. hit C  (Change stalls) at Unisex menu
5. put any value bettwen 1-5 and then enter
6. mbbemu will crash

```
2021-10-31 17:32:49.7394 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 69:ALLDGS
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 69:ALLDGS')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.Run(String moduleName, FarPtr routine, UInt16 channelNumber, Boolean simulateCallFar, Queue`1 initialStackValues)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abortado
```

Screenshots:
![imagen](https://user-images.githubusercontent.com/95441/139600687-93f2a200-9981-4f82-8ba0-0c07f36dda44.png)

![imagen](https://user-images.githubusercontent.com/95441/139600695-a0ed62e4-c240-4e66-bfba-ba2051f7e396.png)

**Comment by ftoledo** [comment]
[wdgbs21i.zip](https://github.com/mbbsemu/MBBSEmu/files/7449794/wdgbs21i.zip)
