### ISSUE TITLE
[WCCMMUD] Majormud - Sysop's WCCMMUD.INI full screen editor crashes at 80 characters

### ISSUE THREAD

**Issue by fletcherm** [mbbsemu/MBBSEmu#545]
**Module Information**
* Identifier WCCMMUD
* Module Name MajorMud
* Version 1.11p

**Describe the bug**

Using the full screen editor to edit `WCCMMUD.INI` (in the sysop menu) crashes the system if the file is > 79 characters.

**To Reproduce**
1. Ensure your BBS user has the `WCCSYSOP` key - this grants access to Majormud's Sysop menu
2. Enter MajorMud and type 'sysop' to enter the sysop menu
3. Type E to edit the `WCCMMUD.INI` file
4. Full screen editor will briefly show, it will look all messed up, and the board will crash with this stacktrace in the background:

```
mbbsemu    | Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
mbbsemu    |    at System.Linq.ThrowHelper.ThrowNoMatchException()
mbbsemu    |    at MBBSEmu.HostProcess.Fsd.FsdUtility.SetAnswers(List`1 answers, List`1 fields)
mbbsemu    |    at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.EnteringFullScreenDisplay(SessionBase session)
mbbsemu    |    at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
mbbsemu    |    at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
mbbsemu    |    at System.Threading.Thread.StartCallback()
```

**Expected behavior**

The board does not crash.

**Software Information:**
- OS: Ubuntu 20.04, Docker, mbbsemu-docker image
- Telnet Client Megamud

**Comment by fletcherm** [comment]
@synacktic I'd appreciate if you could try this with your WG reference system. Mine is all messed up right now.

The game menu does warn "only [edit] if [this file] is small," so being too long could be a known problem...but a hard hard hard crash like this, with that stacktrace, would surprise me.

Would be interesting to see what you get on a reference system.
