### ISSUE TITLE
[MUICHAOS] Swords of Chaos - GameOp player editor crashes system

### ISSUE THREAD

**Issue by Ohmz1290** [mbbsemu/MBBSEmu#547]
**Module Information**
[MUICHAOS]
[Swords of Chaos]
[4.17]

**Describe the bug**
Inside the gameop menu, when editing a player, if you try to use the arrow keys to move to another field, or if you hit enter in the field you're on, it will crash the system.

**To Reproduce**
1. Open Swords of Chaos module and login as a gameop user. (must add key "GAMEOP" to the user account, /sys addkey <user> GAMEOP)
2. Enter the game, then type "gameop<enter>".  Must have special permission "player editor" set to *on*, type "s<enter>0<enter>" to toggle it on/off. "x<enter>" to exit permissions sub-menu.
3. "d<enter>" for player editor. Type in a valid user name and hit enter, your own is fine, then "a<enter>" to edit stats.
4. Hit enter or arrow up or down, and the system will crash.
5. See crash error

**Expected behavior**
Normal behavior is for the editor to go to the next field when you hit enter. Up or down arrows will also normally take you to other fields (arrow down for next field, arrow up for previous field).

Crash Error:
MBBSEmu will crash with error from the gameop player stats editor with the following:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at MBBSEmu.HostProcess.Fsd.FsdUtility.<>c.<BuildAnswerString>b__7_0(FsdFieldSpec field)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 , Func`2 )
   at MBBSEmu.HostProcess.Fsd.FsdUtility.BuildAnswerString(FsdStatus fsdStatus)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.FieldVerificationRoutine(SessionBase session, FsdStatus fieldStatus)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ValidateField(SessionBase session, FsdStatus fsdStatus)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.InFullScreenDisplay(SessionBase session)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.Thread.StartCallback()

**Software Information:**
- OS: [Windows 10 64-bit]
- Telnet Client [Windows CLI telnet, or SecureCRT]

**Comment by enusbaum** [comment]
This could be an error with the FSD as I think the only real template we've ever tested with was MajorMUD's character creation screen. I'll have to take a look at the template used by SOC and see that's up! 👍
